# Generated by Django 5.0.7 on 2024-07-12 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingdata',
            old_name='booked_date',
            new_name='date',
        ),
    ]
